name: Deployment Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  Oxlint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with: 
        node-version: 18
    - name: Instalar dependencias
      run: npm ci

    - name: Instalar Oxlint
      run: npm ci --save-dev oxlint

    - name: Ejecutar Oxlint
      run: npm run lint


  Build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with: 
        node-version: 18
    - name: Instalar dependencias
      run: npm ci
    - name: Build
      run: npm run build
    - uses: actions/upload-artifact@v4
      with:
        name: dist
        path: dist

  Test:
    # Este job depende de Oxlint y Build, por lo que se ejecutará después de ellos
    # Ejecuta los tests unitarios y verifica que el código esté funcionando correctamente
    needs: [Oxlint, Build]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with: 
        node-version: 18
    - name: Instalar dependencias
      run: npm ci
    - uses: actions/download-artifact@v4
      with:
        name: dist
        path: dist
    - name: Test unitario
      run: npm run test

  Deploy:
    # Este job depende de Build, por lo que se ejecutará después de él
    needs: [Test]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with: 
        node-version: 18
    - name: Instalar dependencias
      run: npm ci
    - name: Desplegar a Render
      run: npm render

         
  E2E_Test:
    needs: [Deploy]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with: 
        node-version: 18
    - name: Instalar dependencias
      run: npm ci
    - name: Test de Cypress en modo headless #sin interfaz grafica, npx wait-on https://continuous-integration-rbne.onrender.com 
      run: npm run cypress:run