name: Deployment Pipeline
on:
  push:
    branches: [main]

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
          # Checkout the code  
            - uses: actions/checkout@v4
              with:
                fetch-depth: 0
          # Set up Node.js environment
            - uses: actions/setup-node@v4
              with:
                node-version: '18'
          # Install dependencies 
            - name: Install dependencies
              run: npm install
          # Run Linting
          #  - name: Lint
             # run: npm run eslint
              