name: Deployment Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with: 
        node-version: 18
    - name: Instalar dependencias
      run: npm install
    - name: Instalar Oxlint
      run: npm install --save-dev oxlint
    - name: Ejecutar Oxlint
      run: npm run lint

    - name: Build
      run: npm run build
